AprilBlog2017/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView

from blog.views import article_list
from django.conf import settings

from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', article_list, name="index"),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    url(r'^favicon\.ico$',RedirectView.as_view(url=r'static/img/favicon.ico'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostFeed

urlpatterns = [
    url(r'^$', views.article_list, name='article_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.article_detail, name="article_detail"),
    url(r'^tag/(?P<tag_slug>.+?)/$', views.tag_detail, name='tag_detail'),
    url(r'^tags/$', views.tag_list, name='tag_list'),
    url(r'^archives/$', views.archives, name='archives'),
    url(r'^about/$', views.aboutme, name='aboutme'),
    url(r'^about/like/$', views.like, name='like'),
    url(r'^feed/$', LatestPostFeed(), name='post_feed')
]

blog/models.py
import os

import re

import datetime

from django.conf import settings
from django.core.files.base import ContentFile
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from taggit.managers import TaggableManager
from unidecode import unidecode

from markdown2 import markdown


def get_path(instance, filename):
    path = os.path.join('blog_md', str(instance.publish.year), str(instance.publish.month), str(instance.publish.day))
    file_path = os.path.join(settings.MEDIA_ROOT, path, filename.replace(' ', '_'))
    if os.path.exists(file_path):
        os.remove(file_path)
    return file_path


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Article(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    author = models.ForeignKey(User, related_name='article', default='1')

    created = models.DateTimeField(auto_now=True)
    updated = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)

    title = models.CharField(max_length=250)
    subtitle = models.CharField(max_length=250, blank=True)
    slug = models.SlugField(max_length=250, unique_for_date='publish', blank=True)
    body = models.TextField(blank=True)  # Markdown format
    html_body = models.TextField(blank=True)
    snippet = models.TextField(blank=True)  # HTML format
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')

    objects = models.Manager()  # The default manager
    published = PublishedManager()

    tags = TaggableManager(blank=True)

    md_file = models.FileField(upload_to=get_path, blank=True)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:article_detail', args=[self.publish.year,
                                                    self.publish.strftime('%m'),
                                                    self.publish.strftime('%d'),
                                                    self.slug])

    def save(self, *args, **kwargs):
        '''
        slug: slugified title (Chinese to Pinyin) 
        body: read from md_file 
        html_body: transformed from Markdown file
        snippet: above the <!-- more --> tag 
        '''

        # slug: slugified title (Chinese to Pinyin)
        self.slug = slugify(unidecode(self.title))

        # body: read from md_file (Markdown format)
        if self.md_file:
            self.body = self.md_file.read()

        # snippet: FROM BODY(Markdown) => HTML
        # body should be utf-8 encoding or unicode because we use regex
        if type(self.body) == bytes:
            body = self.body.decode('utf-8')
        elif type(self.body) == str:
            body = self.body

        # find <!-- more --> tag to get the snippet
        # if no this tag, snippet would be full text
        res = re.search('(.*?)<!-- more -->', body, re.S)
        if res:
            snippet = res.group(1)
        else:
            snippet = body

        # snippet encoding go back to utf-8 to render into html format

        snippet = snippet.encode('utf-8')

        self.snippet = markdown(snippet, extras={'fenced-code-blocks':None,'tables':None,'cuddled-lists':None,'pyshell':None,'html-classes':{'table':'table table-hover table-bordered'}})

        # body
        if type(self.body) == str:
            self.body = self.body.encode('utf-8')

        self.html_body = markdown(self.body, extras={'fenced-code-blocks':None,'tables':None,'cuddled-lists':None,'pyshell':None,'html-classes':{'table':'table table-hover table-bordered'}})


        super(Article, self).save(*args, **kwargs)

blog/views.py
import redis
from collections import defaultdict
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.db.models import Count
from django.conf import settings
from taggit.models import Tag

from .models import Article
from taggit.models import Tag


r = redis.StrictRedis(host=settings.REDIS_HOST,
                      port=settings.REDIS_PORT,
                      db=settings.REDIS_DB)


def article_list(request, tag_slug=None):
    object_list = Article.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'current_page': page,
                                                   'pages': range(1, paginator.num_pages + 1),
                                                   'posts': posts,
                                                   'tag': tag})


def article_detail(request, year, month, day, post):
    post = get_object_or_404(Article, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})


def tag_detail(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = Article.published.filter(tags__in=[tag])
    return render(request, 'blog/post/tag.html', {'tag': tag, 'posts': posts})


def tag_list(request):
    tags = Tag.objects.all()
    return render(request, 'blog/post/tags.html', {'tags': tags})


def archives(request):
    posts_by_year = defaultdict(list)
    articles = Article.published.all()
    for article in articles:
        year = article.publish.year
        posts_by_year[year].append(article)
    posts_by_year = sorted(posts_by_year.items(), reverse=True)
    return render(request, 'blog/post/archives.html', {'posts':posts_by_year})


def aboutme(request):
    about_article = get_object_or_404(Article, status='draft', title='about')
    like_count= r.get('like')
    return render(request, 'blog/post/about.html', {'post': about_article, 'like_count': like_count})


def like(request):
    total_likes = r.incr('like')
    return JsonResponse({'like_count':total_likes})

templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static "css/clean-blog.min.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->

    {#    <link href="{% static "css/font-awesome.css" %}" rel="stylesheet">#}
    <link href="http://libs.baidu.com/fontawesome/4.4.0/css/font-awesome.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Code Static Files -->
    <link href="{% static "css/tomorrow_night_eighties.min.css" %}" rel="stylesheet">
    <link href="//at.alicdn.com/t/font_zs3dd9ii3g1u4n29.css" rel="stylesheet">

    {% block headelse %}{% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="{% url "blog:article_list" %}" id="left_top">
                RoadSheep
            </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url "blog:article_list" %}">
                        <i class="fa fa-home" aria-hidden="true"></i>
                        Home
                    </a>
                </li>
                <li>
                    <a href="{% url "blog:tag_list" %}">
                        <i class="fa fa-tags" aria-hidden="true"></i>
                        Tags
                    </a>
                </li>
                <li>
                    <a href="{% url "blog:archives" %}">
                        <i class="fa fa-archive" aria-hidden="true"></i>
                        Archives
                    </a>
                </li>
                <li>
                    <a href="{% url "blog:aboutme" %}">
                        <i class="fa fa-heart" aria-hidden="true"></i>
                        About
                    </a>
                </li>
                <li>
                    <a href="{% url "blog:post_feed" %}">
                        <i class="fa fa-rss" aria-hidden="true"></i>
                        RSS
                    </a>
                </li>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
{% block header %}
{% endblock %}

<!-- Main Content -->
{% block content %}
{% endblock %}




<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="http://weibo.com/u/6201251338">
                                 <span class="fa-stack fa-lg"> 
                                    <i class="iconfont" style="font-size:2em;width: 100%">&#xe601;</i>
                                 </span> 
                        </a>
                    </li>
                    <li>
                        <a href="https://www.douban.com/people/roadsheep">
                                 <span class="fa-stack fa-lg"> 
                                    <i class="iconfont" style="font-size:2em;width: 100%">&#xe64d;</i>
                                 </span> 
                        </a>
                    </li>
                   <li>
                        <a href="https://www.zhihu.com/people/louisun">
                                 <span class="fa-stack fa-lg"> 
                                    <i class="iconfont" style="font-size:2em;width: 100%">&#xe607;</i>
                                 </span> 
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/louisun">
                                 <span class="fa-stack fa-lg"> 
                                    <i class="iconfont" style="font-size:2em;width: 100%">&#xe70a;</i>
                                 </span> 
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Louis 2017</p>
            </div>
        </div>
    </div>
</footer>

<!-- jQuery -->
<script src="{% static "js/jquery.min.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "js/bootstrap.min.js" %}"></script>

<!-- Theme JavaScript -->
<script src="{% static "js/clean-blog.min.js" %}"></script>

{% block bodyelse %}{% endblock %}

</body>

</html>

templates/blog/post/about.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block title %} About {% endblock %}

{% block header %}
    <header class="intro-header" style="background-image: url({% static "img/about-bg.jpg" %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 style="font-size: 80px;">About Me</h1>
                        <hr class="small" style="visibility: hidden;">
                        <span class="subheading">想像力こそが、すべてを変える</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="postlist">
                    <h2 style="text-align: center; margin-top:20px;">
                        <button class="btn btn-danger btn-large btn-block btn-like-add" id="like"
                                style="width: 120px; border-radius: 100px; margin: 30px auto">Like ❤
                        </button>
                        已有 <span id="like_count">{{ like_count }} </span> Likes
                    </h2>
                    <hr>

                    {{ post.html_body | safe }}

                    <hr>
                    <!-- 来必力City版安装代码 -->
                    <div id="lv-container" data-id="city" data-uid="MTAyMC8yODI1MS80ODIz">
                        <script type="text/javascript">
                            (function (d, s) {
                                var j, e = d.getElementsByTagName(s)[0];

                                if (typeof LivereTower === 'function') {
                                    return;
                                }

                                j = d.createElement(s);
                                j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
                                j.async = true;

                                e.parentNode.insertBefore(j, e);
                            })(document, 'script');
                        </script>
                        <noscript> 为正常使用来必力评论功能请激活JavaScript</noscript>
                    </div>
                    <!-- City版安装代码已完成 -->
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block bodyelse %}
    <script>
        $(document).ready(function () {
            var flag = 1;
            $('.btn-danger').click(function () {
                if (flag) {
                    flag = 0;
                    $(".btn-like-add").removeClass("btn-danger");
                    $(".btn-like-add").addClass("btn-primary");
                    $(".btn-like-add").text("LIKED");
                    $.getJSON('{% url "blog:like" %}',
                        function (data) {
                            $("#like_count").text(data.like_count);
                            $("body").append('<audio ' +
                                'autoplay="autoplay"  loop="loop" preload="auto"' +
                                'src="http://7xj74s.com1.z0.glb.clouddn.com/%E4%BA%94%E6%9C%88%E5%A4%A9%20-%20%E5%A6%82%E6%9E%9C%E6%88%91%E4%BB%AC%E4%B8%8D%E6%9B%BE%E7%9B%B8%E9%81%87.mp3">'+
                                '</audio>')
                            flag = 0;
                        }
                    );
                }
            });
        })
    </script>

{% endblock %}


templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block title %} {{ post.title }} {% endblock %}

{% block header %}
    <header class="intro-header" style="background-image: url({% static "img/post-bg.jpg" %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 style="font-size: 80px;">{{ post.title }}</h1>
                        <hr class="small" style="visibility: hidden;">
                        <h2 class="subheading" style="font-family: Helvetica,Arial">{{ post.subtitle }}
                            <span style="font-weight: bold">{{ post.publish | date:"F d, Y" }}</span>
                        </h2>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div id="taglist">
                    {% for tag in post.tags.all %}
                        <span class="label label-default">
                            <i class="fa fa-tag" aria-hidden="true">&nbsp;</i>
                            <a href="{% url "blog:tag_detail" tag.slug %}" style="font-family: Lora;font-style: italic">{{ tag.name }}</a>
                        </span>
                    {% endfor %}
                </div>

                {{ post.html_body | safe }}
                <hr>
                <!-- 来必力City版安装代码 -->
                <div id="lv-container" data-id="city" data-uid="MTAyMC8yODI1MS80ODIz">
                    <script type="text/javascript">
                        (function (d, s) {
                            var j, e = d.getElementsByTagName(s)[0];

                            if (typeof LivereTower === 'function') {
                                return;
                            }

                            j = d.createElement(s);
                            j.src = 'https://cdn-city.livere.com/js/embed.dist.js';
                            j.async = true;

                            e.parentNode.insertBefore(j, e);
                        })(document, 'script');
                    </script>
                    <noscript> 为正常使用来必力评论功能请激活JavaScript</noscript>
                </div>
                <!-- City版安装代码已完成 -->
            </div>
        </div>
    </div>


{% endblock %}


templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block title %} RoadSheep {% endblock %}

{% block header %}
    <header class="intro-header" style="background-image: url({% static "img/home-bg.jpg" %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Louis's Blog</h1>
                        <hr class="small" style="visibility: hidden;">
                        <span class="subheading">想像力こそが、すべてを変える</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% if tag %}
                    <h2 style="color: cornflowerblue">Articles tagged with "{{ tag.name }}"</h2>
                    <hr>
                {% endif %}
                {% for post in posts %}
                    <div class="post-preview">
                        <a href="{{ post.get_absolute_url }}">
                            <h2 class="post-title">
                                {{ post.title }}
                            </h2>
                        </a>


                        <div id="postbody">
                            {{ post.snippet | safe }}
                        </div>
                        <br>
                        <a href="{{ post.get_absolute_url }}" class="cfx" id="more">
                            <span style="font-family: 'Open Sans',Helvetica">
                               &nbsp;&nbsp;READ MORE&nbsp;&nbsp;
                            </span>
                        </a>
                        <br><br><br>
                        <p class="post-meta">
                            Posted by
                            <span style="font-weight: bold"> {{ post.author }}</span>
                            on <span style="font-weight: bold"> {{ post.publish | date:"N d, Y" }}</span>
                            <span id="tagrow">
                                {% for tag in post.tags.all %}
                                    <span class="label label-default">
                                        <i class="fa fa-tag" aria-hidden="true">&nbsp;</i>
                                        <a href="{% url "blog:tag_detail" tag.slug %}">{{ tag.name }}</a>
                                    </span>
                                {% endfor %}
                            </span>
                        </p>
                    </div>
                    <hr>
                {% endfor %}
                {% with page=posts %}
                    <div class="pager">
                        {% if page.has_previous %}
                            <span class="previous">
                                <a href="?page={{ page.previous_page_number }}">Previous</a>
                            </span>
                        {% else %}
                            <span class="previous">
                                <a href="javascript:void(0);" style="background-color: #3F3C3C; color:white; cursor: default">NO PREVIOUS</a>
                            </span>
                        {% endif %}

                        <span class="current">
                            <span>{{page.number }} of {{ page.paginator.num_pages }}</span>
                        </span>

                        {% if page.has_next %}
                            <span class="next">
                                <a href="?page={{ page.next_page_number }}">Older</a>
                            </span>

                        {% else %}
                            <span class="next">
                                <a href="javascript:void(0);"
                                   style="background-color: #3F3C3C; color:white; cursor: default">THE END
                                </a>
                            </span>
                        {% endif %}
                    </div>
                    {#                    <div>#}
                    {#                        <ul class="pager">#}
                    {#                            {% if page.has_previous %}#}
                    {#                                <li class="previous">#}
                    {#                                    <a href="?page={{ page.previous_page_number }}"> &larr; Previous</a>#}
                    {#                                </li>#}
                    {#                            {% else %}#}
                    {#                                <li class="previous">#}
                    {#                                    <a href="javascript:void(0);"#}
                    {#                                       style="background-color: #3F3C3C; color:white; cursor: default">No#}
                    {#                                        Pre</a>#}
                    {#                                </li>#}
                    {#                            {% endif %}#}
                    {##}
                    {#                            <li class="current" style="text-align: center; padding: 35px"><a style="cursor: default"#}
                    {#                                                                                             id="current">{{ page.number }}#}
                    {#                                of {{ page.paginator.num_pages }}</a></li>#}
                    {##}
                    {#                            {% if page.has_next %}#}
                    {#                                <li class="next">#}
                    {#                                    <a href="?page={{ page.next_page_number }}">Older Posts &rarr;</a>#}
                    {#                                </li>#}
                    {##}
                    {#                            {% else %}#}
                    {#                                <li class="next">#}
                    {#                                    <a href="javascript:void(0);"#}
                    {#                                       style="background-color: #3F3C3C; color:white; cursor: default">THE END#}
                    {#                                    </a>#}
                    {#                                </li>#}
                    {#                            {% endif %}#}
                    {#                        </ul>#}
                    {#                    </div>#}
                {% endwith %}
                <hr>
            </div>
        </div>
    </div>


{% endblock %}


{#{% block pagination %}#}
{#    {% with page_obj=posts %}#}
{#    <nav id="pagination" class="text-center">#}
{#        <ul class="pagination">#}
{#            {% if page_obj.has_previous %}#}
{#                <li><a href="?page={{ page_obj.previous_page_number }}{{ getvars }}{{ hashtag }}" aria-label="Previous"><span#}
{#                        aria-hidden="true">Previous</span></a></li>#}
{#            {% else %}#}
{#                <li class="disabled"><a href="javascript:void(0);" aria-label="Previous"><span aria-hidden="true">Previous</span></a></li>#}
{#            {% endif %}#}
{#            {% for page in pages %}#}
{#                {% if page %}#}
{#                    {% ifequal page page_obj.number %}#}
{#                        <li class="active"><a href="javascript:void(0);">{{ page }} <span class="sr-only">(current)</span></a></li>#}
{#                    {% else %}#}
{#                        <li><a href="?page={{ page }}{{ getvars }}{{ hashtag }}">{{ page }} </a></li>#}
{#                    {% endifequal %}#}
{#                {% else %}#}
{#                    <li><a href="javascript:void(0);">...</a></li>#}
{#                {% endif %}#}
{#            {% endfor %}#}
{#            {% if page_obj.has_next %}#}
{#                <li><a href="?page={{ page_obj.next_page_number }}{{ getvars }}{{ hashtag }}" aria-label="Next"><span#}
{#                        aria-hidden="true">Next</span></a></li>#}
{#            {% else %}#}
{#                <li class="disabled"><a href="javascript:void(0);" aria-label="Next"><span aria-hidden="true">Next</span></a></li>#}
{#                </li>#}
{#            {% endif %}#}
{#        </ul>#}
{#    </nav>#}
{##}
{#    {% endwith %}#}

{#{% endblock %}#}

templates/blog/post/tags.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block title %}Tags{% endblock %}

{% block headelse %}
    <link href="{% static 'css/tagcloud.min.css' %}" rel="stylesheet">
    <script src="{% static 'js/tagcloud.min.js' %}"></script>
{% endblock %}



{% block header %}
    <header class="intro-header" style="background-image: url({% static "img/contact-bg.jpg" %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" style="text-align: center;">
                        <h1 style="font-size: 80px;"> Tag Cloud </h1>
                        <hr class="small" style="visibility: hidden;">
                        <span class="subheading">想像力こそが、すべてを変える</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div style="height: 600px; ">
                <div class="tagcloud">
                    {% for tag in  tags %}
                        <i class="fa fa-tag" aria-hidden="true">
                            <a href="{% url 'blog:tag_detail'  tag.slug %}"
                               style="font-family: Lora;font-weight: bold"> {{ tag.name }}</a>
                        </i>
                    {% endfor %}
                </div>
            </div>

        </div>
    </div>


{% endblock %}


{% block bodyelse %}
    <script type="text/javascript">
        tagcloud({fontsize: 20, radius: 150,});
    </script>
{% endblock %}